# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d28d7513c4171af3de42a98454721b2705718cc553a82d9c21da9e0e32baf7b8e31d4ecc78bf38853377c67bb36cce3f701b5aaa59db7cc7c3969dbbdd79c578

test:
  secret_key_base: 5af38a2555019cdb08402c96d50d8c9eb7c847f42178614889b52b8e4401469c8c58d0abe27f936ddfba2ddc4565830d41064cf6109b6bb06687bf987c99391e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
